config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events do
    resources :event_attendees, only: [:create]
  end

  resources :users, only: [:show]
  get 'events/index'
  root 'events#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  scope :past, -> { where('date < ?', DateTime.now) }
  scope :upcoming, -> { where('date > ?', DateTime.now) }

  has_many :event_attendees, foreign_key: 'event_id'
  has_many :attendees, through: :event_attendees, source: :attendee
end

app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :event, class_name: 'Event'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events, foreign_key: 'creator_id', class_name: 'Event'
  has_many :event_attendees, foreign_key: 'attendee_id'
  has_many :attending_events, through: :event_attendees, source: :event

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name password email])
  end
end

app/controllers/event_attendees_controller.rb
class EventAttendeesController < ApplicationController
  def create
    event = Event.find(params[:event_id])
    attended = event.event_attendees.find_by(attendee_id: current_user.id)
    redirect_to event_path(event) and return if attended

    @event_attendee = event.event_attendees.build(attendee_id: current_user.id)
    redirect_to event_path(event) and return if @event_attendee.save

    redirect_to event_path(event)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: %i[create new]

  def new
    @event = Event.new
  end

  def index
    @events = Event.all.order('created_at DESC')
    @upcoming = Event.upcoming
    @past = Event.past
  end

  def create
    user = User.find(current_user.id)
    user.events
    @event = user.events.build(event_params)

    if @event.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  private

  def event_params
    params.require(:event).permit(:name, :date)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @created_events = @user.events
    @past_events = @user.attending_events.past
    @upcoming_events = @user.attending_events.upcoming
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendees_helper.rb
module EventAttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<div class="container">
    <div class="container pl-3">
        <h1 class="h3 ">Events</h1>

        <%= link_to "New Event", new_event_path, class:"btn btn-primary mx-1" %>
    </div>
    <div class="container row mt-5">
        <div class="col md-6 ">
            <h1 class="h3">Upcoming</h1>
            <% @upcoming.each do |event| %>
            <div class="card w-100 mb-2">
                <div class="card-body">
                    <h5 class="card-title"><%= event.name %></h5>
                    <p class="card-text"><%= event.date %></p>
                    <br />
                    <%=link_to "View event", event_path(event), class:"btn btn-primary mt-3" %>
                </div>
            </div>
            <%end %>
        </div>
        <div class="col md-6">
            <h1 class="h3">Past</h1>
            <% @past.each do |event| %>
            <div class="card w-100 mb-2">
                <div class="card-body">
                    <h5 class="card-title"><%= event.name %></h5>
                    <p class="card-text"><%= event.date %></p>
                    <br />
                    <%=link_to "View event", event_path(event), class:"btn btn-primary mt-3" %>
                </div>
            </div>
            <%end %>
        </div>
    </div>
</div>

app/views/events/new.html.erb
<div class="container w-50">
    <h4>Add new event</h4>
    <%= form_with model: @event do |f| %>
    <div class="mb-3">
        <%= f.label :name, "Name: ", class:"form-label" %>
        <%= f.text_field :name, class:"form-control" %>
    </div>
    <div class="mb-3">
        <%= f.label :date, "Date: ", class:"form-label"%>
        <%= f.date_field :date, class: "form-control" %>
    </div>
    <div class="mb-3">
        <%= f.submit class: "btn btn-primary" %>
    </div>
    <% end %>
    <%= link_to "Back", root_path, class: "btn btn-secondary" %>

    <div>

app/views/events/show.html.erb
<div class="container">
    <figure class="figure">
        <h1 class="h3">Event details</h1>

        <div class="">
            <div class="mb-2">
                <strong>Event name: </strong> <%= @event.name %>
            </div>
            <div class="mb-2">
                <strong>Event date: </strong> <%= @event.date %>
            </div>
            <%if current_user %>
            <%= link_to "Attend", event_event_attendees_path(@event), method: :post, class:"btn btn-primary" %>
            <%end %>

            <div>
                <h1>Attendees</h1>
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Email</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @event.event_attendees.each do |a| %>
                        <tr>
                            <td><%=link_to  a.attendee.name, user_path(a.attendee) %></td>
                            <td><%= a.attendee.email %></td>
                        </tr>
                        <% end %>
                    </tbody>
                </table>

            </div>

            <%= link_to "Back", root_path, class:"btn btn-secondary" %>


    </figure>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <%= render "shared/header" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
</body>

</html>

app/views/shared/_header.html.erb
 <nav class="navbar navbar-expand-lg navbar-dark bg-primary" id="navigation">
     <div class="container">
         <%= link_to "Private Events", root_path , class:"navbar-brand"%>
         <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
             <span class="navbar-toggler-icon"></span>
         </button>
         <div class="collapse navbar-collapse" id="navbarSupportedContent">
             <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                 <% if current_user %>
                 <li class="nav-item">
                     <%= link_to current_user.name, user_path(current_user), class:"nav-link" %>
                 </li>
                 <li class="nav-item">
                     <%= link_to "Logout", destroy_user_session_path, method: :delete, class:"nav-link" %>
                 </li>
                 <%else %>
                 <li class="nav-item">
                     <%= link_to "Login", new_user_session_path, class:"nav-link active" %>
                 </li>
                 <li class="nav-item">
                     <%= link_to "Signup", new_user_registration_path, class:"nav-link" %>
                 </li>
                 <%end %>
             </ul>

         </div>
     </div>
 </nav>

app/views/users/show.html.erb
<div class="container pb-5">
    <h4><strong>Name: </strong><%= @user.name %></h4>
    <h4><strong>Email: </strong><%= @user.email %></h4>
    <hr />
    <div class="row">
        <div class="col md-12">
            <h3>Created Events</h3>
            <hr />
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Date</th>
                        <th scope="col">Status</th>
                        <th scope="col">Created at</th>

                    </tr>
                </thead>
                <tbody>
                    <% @created_events.each do |e, index| %>
                    <tr>
                        <td><%= e.name %></td>
                        <td><%= e.date %></td>
                        <td><%= e.date > DateTime.now ? "Upcoming" : "Past" %></td>
                        <td><%= e.created_at %></td>
                    </tr>
                    <%end%>
                </tbody>
            </table>
        </div>
    </div>
    <br/>
    <br/>
    <br/>
    <div class="row">
            <h3>Attending Events</h3>
            <hr />
            <div class="row">
            <div class="col md-6">
            <h5>Attended Events (Past)</h5>
            <hr />
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Date</th>
                            <th scope="col">Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @past_events.each_with_index do |e, index| %>
                        <tr>
                            <td>#<%= index+1 %></td>
                            <td><%= e.name %></td>
                            <td><%= e.date %></td>
                        </tr>
                        <%end%>
                    </tbody>
                </table>
            </div>
            <div class="col md-6">
            <h5>Attending Events (Upcoming)</h5>
            <hr/>
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Date</th>
                            <th scope="col">Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @upcoming_events.each_with_index do |e, index| %>
                        <tr>
                            <td>#<%= index+1 %></td>
                            <td><%= e.name %></td>
                            <td><%= e.date %></td>
                        </tr>
                        <%end%>
                    </tbody>
                </table>
            </div>
            </div>
        </div>

</div>